# Generated by Django 4.2.4 on 2023-09-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='floor',
        ),
        migrations.AddField(
            model_name='floor',
            name='garage',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='garage_floor', to='sensors.garage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floor',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
    ]
